CREATE SCHEMA IF NOT EXISTS ###APP_NAME###db /*!40100 DEFAULT CHARACTER SET
utf8mb4 COLLATE utf8mb4_unicode_ci */;
USE ###APP_NAME###db;
DROP USER IF EXISTS '###APP_NAME###dbadmin';
CREATE USER IF NOT EXISTS '###APP_NAME###dbadmin'@'%' IDENTIFIED BY '###DB_PASSWD###';
GRANT ALL ON ###APP_NAME###db.* TO '###APP_NAME###dbadmin'@'%';
FLUSH PRIVILEGES;
